version: '2'
services:
  apiofertas-app:
    image: apiofertas
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://apiofertas-mysql:3306/apiofertas?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://apiofertas-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://apiofertas-elasticsearch:9200
    ports:
      - 8080:8080
  apiofertas-mysql:
    extends:
      file: mysql.yml
      service: apiofertas-mysql
  apiofertas-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: apiofertas-elasticsearch
